version: '2'

services:
  chatter-server:
    image: chatter-server
    container_name: chatter-server
    restart: always
    networks:
      chat-network:
        ipv4_address: 172.10.0.2

  chatter-web:
    image: chatter-web
    container_name: chatter-web
    networks:
      chat-network:
        ipv4_address: 172.10.0.3


networks:
  chat-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.0.1